"""pipeline_code — Phase 13 S7: перший реальний pipeline (DOMAIN_CODE).

Перетворює `TaskSpec` з домену `code` у виконуваний `Plan` з реальних
handler-ів `TaskRunner` (`run_command` / `write_file`). Без LLM-викликів
на етапі compile — детерміноване розгортання з шаблонів. LLM-генерація
коду/тестів приходить у S9 через cross-AI actors (Codex/ChatGPT/Windsurf).

Структура Plan, яку генерує `CodePipeline`:

    1) mkdir_output_dir      — `run_command: mkdir -p {output_dir}`
    2) per deliverable       — `write_file {output_dir}/{filename}` з
                                placeholder-контентом (docstring + TODO).
    3) pytest (опційно)      — `run_command: pytest {output_dir}`
                                якщо `_wants_tests(spec)` повертає True.
    4) ruff check (опційно)  — `run_command: ruff check {output_dir}`
                                якщо `_wants_lint(spec)` повертає True.

Всі `run_command` кроки мають `expect=[return_code=0]` → `TaskRunner`
позначить STEP_EXPECT_FAILED якщо exit-код ненульовий. Всі `write_file`
кроки мають `expect=[file_exists]` → санітарна перевірка після запису.

`required_tools(spec)` віддає список kind-ів / зовнішніх утиліт, потрібних
для виконання (для QuotaTracker у S9 та для precheck у GUI).

Контракти pipeline-а: див. `functions/core_plan_compiler.Pipeline`.
"""
from __future__ import annotations

import re
import shlex
from dataclasses import dataclass
from typing import Any, Dict, List

from .core_task_intake import DOMAIN_CODE, TaskSpec
from .logic_expectations import (
    EXPECT_FILE_EXISTS,
    EXPECT_RETURN_CODE,
    ExpectSpec,
)
from .logic_task_runner import ON_ERROR_SKIP, ON_ERROR_STOP, Plan, Task

# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------

DEFAULT_OUTPUT_DIR_PREFIX = "workspace"
DEFAULT_TEST_TIMEOUT_S = 120.0
DEFAULT_LINT_TIMEOUT_S = 60.0

_TEST_HINT_RE = re.compile(
    r"\b(tests?|pytest|unit[\s_\-]?tests?|specs?|tdd)\b", re.IGNORECASE
)
_LINT_HINT_RE = re.compile(r"\b(lint|ruff|flake8|pep[\s_\-]?8|style|pylint)\b", re.IGNORECASE)
_TESTLIKE_FILENAME_RE = re.compile(r"test_|_test\.py|^test\.py", re.IGNORECASE)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _wants_tests(spec: TaskSpec) -> bool:
    """Чи треба додавати pytest-крок у Plan."""
    for item in spec.deliverables:
        if _TEST_HINT_RE.search(item):
            return True
        if _TESTLIKE_FILENAME_RE.search(item):
            return True
    for c in spec.constraints:
        if _TEST_HINT_RE.search(c):
            return True
    if _TEST_HINT_RE.search(spec.goal):
        return True
    return False


def _wants_lint(spec: TaskSpec) -> bool:
    """Чи треба додавати ruff-check крок у Plan."""
    for c in spec.constraints:
        if _LINT_HINT_RE.search(c):
            return True
    return False


def _derive_filename(deliv: str, idx: int) -> str:
    """Витягнути з рядка deliverable сане ім'я .py файлу.

    Пріоритети:
    - Якщо в рядку є токен що виглядає як ім'я файлу (`foo.py`/`bar.txt`)
      — беремо його як є (перший збіг).
    - Інакше будуємо `deliverable_{idx}_{slug}.py` зі slug-ом з перших
      3 «слов» (alphanumeric tokens).
    """
    file_match = re.search(r"[\w\-./]+\.(py|md|txt|json|yaml|yml|toml|ini|cfg)", deliv)
    if file_match:
        fname = file_match.group(0)
        # Normalize path separators and strip leading ./
        fname = fname.lstrip("./").replace("\\", "/")
        # If relative path with dirs, keep it; otherwise just the file
        return fname

    # fallback: slug
    tokens = re.findall(r"[A-Za-z0-9]+", deliv)
    slug = "_".join(t.lower() for t in tokens[:3]) if tokens else "module"
    slug = slug[:40] or "module"
    return f"deliverable_{idx}_{slug}.py"


def _scaffold_content(deliv: str, spec: TaskSpec, filename: str) -> str:
    """Згенерувати placeholder-контент для файлу.

    Для `.py` — модуль з docstring + TODO. Для інших розширень — проста
    текстова заглушка. Реальне наповнення прийде у S9 (LLM actors).
    """
    if filename.endswith(".py"):
        safe_goal = spec.goal.replace('"', "'")
        safe_deliv = deliv.replace('"', "'")
        lines = [
            '"""Scaffold generated by pipeline_code (Phase 13 S7).',
            "",
            f"Goal: {safe_goal}",
            f"Deliverable: {safe_deliv}",
            f"Task ID: {spec.task_id}",
            "",
            "TODO: implement. Real code-generation is wired in S9 via",
            "cross-AI actors (Codex / ChatGPT / Windsurf). For now this",
            "is an empty scaffold so pytest/ruff have something to lint.",
            '"""',
            "",
            "",
            "def _todo() -> None:",
            f'    """Placeholder for {safe_deliv}."""',
            "    raise NotImplementedError(",
            f'        "Deliverable not implemented yet: {safe_deliv}"',
            "    )",
            "",
        ]
        return "\n".join(lines)
    if filename.endswith(".md"):
        return (
            f"# {deliv}\n\n"
            f"Scaffold generated by pipeline_code (Phase 13 S7).\n\n"
            f"- Goal: {spec.goal}\n"
            f"- Task ID: {spec.task_id}\n\n"
            "TODO: fill in.\n"
        )
    # generic
    return (
        f"Scaffold generated by pipeline_code (Phase 13 S7).\n"
        f"Deliverable: {deliv}\n"
        f"Goal: {spec.goal}\n"
        f"Task ID: {spec.task_id}\n"
        "TODO: fill in.\n"
    )


def _resolve_output_dir(spec: TaskSpec) -> str:
    """Обчислити output_dir для плану (dedicated sub-dir якщо spec порожній)."""
    raw = (spec.output_dir or "").strip()
    if raw:
        # normalize trailing slash
        return raw.rstrip("/").rstrip("\\")
    return f"{DEFAULT_OUTPUT_DIR_PREFIX}/{spec.task_id}"


def _quote(s: str) -> str:
    """Shell-quote (UNIX-style)."""
    return shlex.quote(s)


def _file_path_join(dirpath: str, filename: str) -> str:
    """Cross-platform-safe join — завжди через `/` (run_command через shell)."""
    left = dirpath.rstrip("/").rstrip("\\")
    right = filename.lstrip("/").lstrip("\\")
    return f"{left}/{right}"


# ---------------------------------------------------------------------------
# CodePipeline
# ---------------------------------------------------------------------------


@dataclass
class CodePipeline:
    """Phase 13 S7: реальний pipeline для `DOMAIN_CODE`.

    Config-прапори:
    - `force_tests` / `force_lint` — примусово вмикає ці кроки незалежно
      від `spec.constraints`/`deliverables`.
    - `pytest_cmd` / `ruff_cmd` — перекривають дефолтні команди
      (корисно коли проект використовує `poetry run pytest` тощо).
    - `test_timeout_s` / `lint_timeout_s` — таймаути subprocess-у.
    """

    name: str = "code"
    force_tests: bool = False
    force_lint: bool = False
    pytest_cmd: str = "pytest"
    ruff_cmd: str = "ruff check"
    test_timeout_s: float = DEFAULT_TEST_TIMEOUT_S
    lint_timeout_s: float = DEFAULT_LINT_TIMEOUT_S

    def compile(self, spec: TaskSpec) -> Plan:
        output_dir = _resolve_output_dir(spec)
        tasks: List[Task] = []

        # 1) mkdir output dir
        tasks.append(
            Task(
                id="t1_mkdir",
                kind="run_command",
                name=f"Ensure output dir exists: {output_dir}",
                params={
                    "cmd": f"mkdir -p {_quote(output_dir)}",
                    "shell": True,
                    "reason": "pipeline_code: scaffold output dir",
                    "timeout": 10.0,
                },
                expect=[ExpectSpec(kind=EXPECT_RETURN_CODE, params={"value": 0})],
                on_error=ON_ERROR_STOP,
            )
        )

        # 2) per-deliverable scaffolds
        deliverables = list(spec.deliverables) if spec.deliverables else [spec.goal]
        filenames: List[str] = []
        seen: Dict[str, int] = {}
        for idx, deliv in enumerate(deliverables, start=1):
            filename = _derive_filename(deliv, idx)
            # de-dupe if two deliverables collide on filename
            if filename in seen:
                seen[filename] += 1
                base, dot, ext = filename.rpartition(".")
                filename = f"{base}_{seen[filename]}.{ext}" if dot else f"{filename}_{seen[filename]}"
            else:
                seen[filename] = 1
            filenames.append(filename)
            path = _file_path_join(output_dir, filename)
            content = _scaffold_content(deliv, spec, filename)
            tasks.append(
                Task(
                    id=f"t{len(tasks) + 1}_scaffold_{idx}",
                    kind="write_file",
                    name=f"Scaffold: {deliv}"[:200],
                    params={
                        "path": path,
                        "content": content,
                    },
                    expect=[
                        ExpectSpec(kind=EXPECT_FILE_EXISTS, params={"path": path}),
                    ],
                    on_error=ON_ERROR_STOP,
                    depends_on=["t1_mkdir"],
                )
            )

        # 3) pytest (optional)
        if self.force_tests or _wants_tests(spec):
            tasks.append(
                Task(
                    id=f"t{len(tasks) + 1}_pytest",
                    kind="run_command",
                    name=f"Run tests ({self.pytest_cmd}) on {output_dir}",
                    params={
                        "cmd": f"{self.pytest_cmd} {_quote(output_dir)}",
                        "shell": True,
                        "reason": "pipeline_code: run pytest",
                        "timeout": self.test_timeout_s,
                    },
                    expect=[ExpectSpec(kind=EXPECT_RETURN_CODE, params={"value": 0})],
                    on_error=ON_ERROR_STOP,
                )
            )

        # 4) ruff lint (optional; non-blocking)
        if self.force_lint or _wants_lint(spec):
            tasks.append(
                Task(
                    id=f"t{len(tasks) + 1}_ruff",
                    kind="run_command",
                    name=f"Lint ({self.ruff_cmd}) on {output_dir}",
                    params={
                        "cmd": f"{self.ruff_cmd} {_quote(output_dir)}",
                        "shell": True,
                        "reason": "pipeline_code: run ruff check",
                        "timeout": self.lint_timeout_s,
                    },
                    expect=[ExpectSpec(kind=EXPECT_RETURN_CODE, params={"value": 0})],
                    # lint-fail не повинен завалювати весь code-потік
                    on_error=ON_ERROR_SKIP,
                )
            )

        metadata: Dict[str, Any] = {
            "pipeline": self.name,
            "domain": DOMAIN_CODE,
            "task_id": spec.task_id,
            "output_dir": output_dir,
            "filenames": list(filenames),
            "tests_enabled": bool(self.force_tests or _wants_tests(spec)),
            "lint_enabled": bool(self.force_lint or _wants_lint(spec)),
            "s7_note": (
                "code_pipeline S7 MVP: детерміновані scaffold-и + pytest/ruff. "
                "Контент файлів — TODO placeholder; реальна LLM-генерація приходить "
                "у S9 (cross-AI actors)."
            ),
        }
        return Plan(
            name=f"code plan: {spec.goal}"[:200],
            tasks=tasks,
            metadata=metadata,
        )

    def required_tools(self, spec: TaskSpec) -> List[str]:
        tools: List[str] = ["run_command", "write_file"]
        if self.force_tests or _wants_tests(spec):
            # мітка «треба утиліта pytest»; кроки виконує run_command
            tools.append("pytest")
        if self.force_lint or _wants_lint(spec):
            tools.append("ruff")
        return tools


__all__ = [
    "CodePipeline",
    "DEFAULT_OUTPUT_DIR_PREFIX",
    "DEFAULT_TEST_TIMEOUT_S",
    "DEFAULT_LINT_TIMEOUT_S",
]
