"""Тести для functions/core_task_intake.py — Phase 13.1."""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from functions.core_task_intake import (  # noqa: E402
    ALLOWED_DOMAINS,
    DOMAIN_CODE,
    DOMAIN_MIXED,
    DOMAIN_PHOTO_BATCH,
    DOMAIN_UNKNOWN,
    PERMISSION_AUTO_ALL,
    PERMISSION_CONFIRM_EACH,
    BudgetHints,
    Clarification,
    IntakeError,
    IntakeResult,
    TaskSpec,
    create_task_spec_from_tz,
    load_task_spec,
    parse_intake_response,
    save_task_spec,
)
from functions.logic_ai_adapter import (  # noqa: E402
    CallableProvider,
    ChatRequest,
    ChatResponse,
)
from functions.logic_provider_registry import ProviderRegistry  # noqa: E402


# ---------------------------------------------------------------------------
# BudgetHints
# ---------------------------------------------------------------------------


class TestBudgetHints:
    def test_defaults_are_none(self):
        b = BudgetHints()
        assert b.max_hours is None
        assert b.max_cost_usd is None
        assert b.max_ai_calls is None

    def test_negative_values_normalized_to_none(self):
        b = BudgetHints(max_hours=-1, max_cost_usd=0, max_ai_calls=-5)
        assert b.max_hours is None
        assert b.max_cost_usd is None
        assert b.max_ai_calls is None

    def test_positive_values_kept(self):
        b = BudgetHints(max_hours=3.0, max_cost_usd=5.0, max_ai_calls=100)
        assert b.max_hours == 3.0
        assert b.max_cost_usd == 5.0
        assert b.max_ai_calls == 100


# ---------------------------------------------------------------------------
# TaskSpec
# ---------------------------------------------------------------------------


class TestTaskSpec:
    def test_empty_goal_raises(self):
        with pytest.raises(ValueError):
            TaskSpec(goal="")
        with pytest.raises(ValueError):
            TaskSpec(goal="   ")

    def test_unknown_domain_normalized(self):
        s = TaskSpec(goal="g", domain="martian")
        assert s.domain == DOMAIN_UNKNOWN

    def test_all_allowed_domains_pass(self):
        for d in ALLOWED_DOMAINS:
            s = TaskSpec(goal="g", domain=d)
            assert s.domain == d

    def test_unknown_permission_normalized(self):
        s = TaskSpec(goal="g", permission_mode="wild")
        assert s.permission_mode == PERMISSION_CONFIRM_EACH

    def test_task_id_autogenerated(self):
        s = TaskSpec(goal="g")
        assert s.task_id.startswith("task_")
        assert s.created_at > 0

    def test_task_id_preserved_when_provided(self):
        s = TaskSpec(goal="g", task_id="task_custom_abc", created_at=1234.0)
        assert s.task_id == "task_custom_abc"
        assert s.created_at == 1234.0

    def test_goal_trimmed(self):
        s = TaskSpec(goal="   hello   ")
        assert s.goal == "hello"

    def test_to_dict_round_trip(self):
        original = TaskSpec(
            goal="Django CRUD",
            domain=DOMAIN_CODE,
            domain_sub="django",
            deliverables=["models.py", "views.py"],
            preferred_ai_order=["codex", "windsurf"],
            permission_mode=PERMISSION_AUTO_ALL,
            budget=BudgetHints(max_hours=3.0, max_cost_usd=1.0),
            input_files=["a.py"],
            output_dir="out/",
            raw_tz="TZ text",
        )
        payload = original.to_dict()
        assert payload["goal"] == "Django CRUD"
        assert payload["budget"]["max_hours"] == 3.0
        restored = TaskSpec.from_dict(payload)
        assert restored.goal == original.goal
        assert restored.domain == original.domain
        assert restored.deliverables == original.deliverables
        assert restored.preferred_ai_order == original.preferred_ai_order
        assert restored.permission_mode == original.permission_mode
        assert restored.budget.max_hours == 3.0
        assert restored.task_id == original.task_id

    def test_from_dict_missing_goal_raises(self):
        with pytest.raises(ValueError):
            TaskSpec.from_dict({"goal": ""})


# ---------------------------------------------------------------------------
# parse_intake_response
# ---------------------------------------------------------------------------


def _make_llm_json(**fields):
    default = {"goal": "Do thing", "domain": "code"}
    default.update(fields)
    return json.dumps(default, ensure_ascii=False)


class TestParseIntakeResponse:
    def test_plain_json(self):
        raw = _make_llm_json()
        result = parse_intake_response(raw, raw_tz="original tz")
        assert result.spec is not None
        assert result.spec.goal == "Do thing"
        assert result.spec.domain == DOMAIN_CODE
        assert result.spec.raw_tz == "original tz"
        assert result.pending_questions == []

    def test_json_in_markdown_fence(self):
        raw = "Some preamble\n```json\n" + _make_llm_json() + "\n```\nPostscript"
        result = parse_intake_response(raw, raw_tz="x")
        assert result.spec is not None
        assert result.spec.goal == "Do thing"

    def test_json_with_llm_tokens(self):
        raw = (
            "<|channel|>final<|message|>"
            + _make_llm_json(domain="photo_batch")
            + "<|end|>"
        )
        result = parse_intake_response(raw, raw_tz="x")
        assert result.spec is not None
        assert result.spec.domain == DOMAIN_PHOTO_BATCH

    def test_clarification_questions_extracted(self):
        raw = json.dumps(
            {
                "goal": "unclear",
                "domain": "unknown",
                "clarification_questions": [
                    {"question": "Які файли обробляти?", "options": ["JPG", "PNG"]},
                    {"question": "Куди зберігати?"},
                ],
            },
            ensure_ascii=False,
        )
        result = parse_intake_response(raw, raw_tz="x")
        assert result.spec is not None
        assert len(result.pending_questions) == 2
        assert result.pending_questions[0].question == "Які файли обробляти?"
        assert result.pending_questions[0].options == ["JPG", "PNG"]
        assert result.pending_questions[1].question == "Куди зберігати?"
        assert result.pending_questions[1].options == []

    def test_clarification_as_plain_strings(self):
        raw = json.dumps(
            {
                "goal": "unclear",
                "domain": "unknown",
                "clarification_questions": ["Що саме?", " "],
            }
        )
        result = parse_intake_response(raw, raw_tz="x")
        assert len(result.pending_questions) == 1
        assert result.pending_questions[0].question == "Що саме?"

    def test_no_json_raises(self):
        with pytest.raises(IntakeError):
            parse_intake_response("not json at all", raw_tz="x")

    def test_malformed_json_raises(self):
        with pytest.raises(IntakeError):
            parse_intake_response("{not: valid json}", raw_tz="x")

    def test_invalid_spec_with_clarifications_returns_result(self):
        raw = json.dumps(
            {
                "goal": "",
                "domain": "unknown",
                "clarification_questions": [{"question": "Мета?"}],
            }
        )
        result = parse_intake_response(raw, raw_tz="x")
        assert result.spec is None
        assert len(result.pending_questions) == 1

    def test_invalid_spec_without_clarifications_raises(self):
        raw = json.dumps({"goal": "", "domain": "unknown"})
        with pytest.raises(IntakeError):
            parse_intake_response(raw, raw_tz="x")

    def test_previous_clarifications_recorded_in_spec(self):
        raw = _make_llm_json()
        prev = [Clarification(question="q1", answer="a1")]
        result = parse_intake_response(
            raw, raw_tz="x", previous_clarifications=prev
        )
        assert result.spec is not None
        assert len(result.spec.clarifications) == 1
        assert result.spec.clarifications[0].answer == "a1"

    def test_budget_parsed(self):
        raw = json.dumps(
            {
                "goal": "g",
                "domain": "code",
                "budget": {"max_hours": 2.5, "max_cost_usd": 1.0, "max_ai_calls": 10},
            }
        )
        result = parse_intake_response(raw, raw_tz="x")
        assert result.spec is not None
        assert result.spec.budget.max_hours == 2.5
        assert result.spec.budget.max_cost_usd == 1.0
        assert result.spec.budget.max_ai_calls == 10

    def test_scalar_json_raises(self):
        with pytest.raises(IntakeError):
            parse_intake_response("[1,2,3]", raw_tz="x")


# ---------------------------------------------------------------------------
# create_task_spec_from_tz (with mock ProviderRegistry)
# ---------------------------------------------------------------------------


def _registry_with_scripted_responses(responses):
    """Реєстр з одним CallableProvider, який повертає відповіді по черзі."""
    responses = list(responses)
    calls = []

    def handler(request: ChatRequest):
        calls.append(request)
        if not responses:
            return "no more scripted responses"
        next_resp = responses.pop(0)
        if isinstance(next_resp, ChatResponse):
            return next_resp
        return next_resp

    provider = CallableProvider(handler=handler)
    reg = ProviderRegistry()
    reg.register(provider)
    return reg, calls


class TestCreateTaskSpec:
    def test_happy_path_single_round(self):
        reg, calls = _registry_with_scripted_responses(
            [_make_llm_json(goal="Django CRUD", domain="code")]
        )
        spec = create_task_spec_from_tz("Напиши CRUD для User", registry=reg)
        assert spec.goal == "Django CRUD"
        assert spec.domain == DOMAIN_CODE
        assert spec.raw_tz == "Напиши CRUD для User"
        assert len(calls) == 1

    def test_empty_tz_raises(self):
        reg, _ = _registry_with_scripted_responses([])
        with pytest.raises(ValueError):
            create_task_spec_from_tz("   ", registry=reg)

    def test_provider_error_raises_intake_error(self):
        def failing_handler(request: ChatRequest):
            return ChatResponse(finish_reason="error", error="boom")

        reg = ProviderRegistry()
        reg.register(CallableProvider(handler=failing_handler))
        with pytest.raises(IntakeError):
            create_task_spec_from_tz("something", registry=reg)

    def test_clarification_round_then_resolved(self):
        q_response = json.dumps(
            {
                "goal": "unclear",
                "domain": "unknown",
                "clarification_questions": [
                    {"question": "Який стек?", "options": ["Django", "Flask"]}
                ],
            }
        )
        final_response = _make_llm_json(goal="Django CRUD", domain="code")
        reg, calls = _registry_with_scripted_responses([q_response, final_response])
        answers = []

        def ask_user(question: str, options):
            answers.append((question, tuple(options)))
            return "Django"

        spec = create_task_spec_from_tz(
            "напиши crud",
            registry=reg,
            ask_user=ask_user,
        )
        assert spec.domain == DOMAIN_CODE
        assert len(calls) == 2
        assert answers == [("Який стек?", ("Django", "Flask"))]
        assert len(spec.clarifications) == 1
        assert spec.clarifications[0].answer == "Django"

    def test_clarification_without_ask_user_breaks_loop(self):
        """Якщо є clarifications але нема ask_user — беремо spec як є."""
        with_q = json.dumps(
            {
                "goal": "tentative",
                "domain": "code",
                "clarification_questions": [{"question": "щось?"}],
            }
        )
        reg, calls = _registry_with_scripted_responses([with_q])
        spec = create_task_spec_from_tz("TZ", registry=reg, ask_user=None)
        assert spec.goal == "tentative"
        assert len(calls) == 1

    def test_max_rounds_exhausted_raises(self):
        """Якщо LLM нескінченно просить уточнення і в кожному раунді spec=None."""
        always_invalid = json.dumps(
            {
                "goal": "",
                "domain": "unknown",
                "clarification_questions": [{"question": "?"}],
            }
        )
        reg, _ = _registry_with_scripted_responses([always_invalid] * 5)

        def ask_user(q, opts):
            return ""

        with pytest.raises(IntakeError):
            create_task_spec_from_tz(
                "TZ",
                registry=reg,
                ask_user=ask_user,
                max_rounds=2,
            )

    def test_invalid_max_rounds(self):
        reg, _ = _registry_with_scripted_responses([])
        with pytest.raises(ValueError):
            create_task_spec_from_tz("TZ", registry=reg, max_rounds=0)

    def test_save_to_writes_json(self, tmp_path: Path):
        reg, _ = _registry_with_scripted_responses(
            [_make_llm_json(goal="g", domain="code")]
        )
        out = tmp_path / "subdir" / "spec.json"
        spec = create_task_spec_from_tz("TZ", registry=reg, save_to=out)
        assert out.exists()
        payload = json.loads(out.read_text(encoding="utf-8"))
        assert payload["goal"] == spec.goal
        assert payload["task_id"] == spec.task_id

    def test_permission_auto_all_detected(self):
        """Якщо LLM повернув auto_all — воно зберігається."""
        reg, _ = _registry_with_scripted_responses(
            [
                json.dumps(
                    {"goal": "g", "domain": "code", "permission_mode": "auto_all"}
                )
            ]
        )
        spec = create_task_spec_from_tz("TZ", registry=reg)
        assert spec.permission_mode == PERMISSION_AUTO_ALL


# ---------------------------------------------------------------------------
# save_task_spec / load_task_spec
# ---------------------------------------------------------------------------


class TestPersistence:
    def test_round_trip(self, tmp_path: Path):
        spec = TaskSpec(
            goal="round trip",
            domain=DOMAIN_MIXED,
            deliverables=["a", "b"],
            budget=BudgetHints(max_hours=1.0),
        )
        path = tmp_path / "spec.json"
        save_task_spec(spec, path)
        loaded = load_task_spec(path)
        assert loaded.goal == spec.goal
        assert loaded.domain == DOMAIN_MIXED
        assert loaded.deliverables == ["a", "b"]
        assert loaded.budget.max_hours == 1.0
        assert loaded.task_id == spec.task_id

    def test_save_creates_parent_dirs(self, tmp_path: Path):
        spec = TaskSpec(goal="g")
        deep = tmp_path / "a" / "b" / "c" / "spec.json"
        save_task_spec(spec, deep)
        assert deep.exists()
