cdp_port: 9222
chrome_executable_path: C:\Program Files\Google\Chrome\Application\chrome.exe
chrome_launch_timeout: 15
connect_via_cdp: true
gemini_url: https://gemini.google.com/
hotkey_new_chat: ctrl_shift_o
input_folder: "D:/Python/TEXT/translation/7/output/output/output"
log_formats:
- txt
#- json
manual_tag: _check
max_retries: 3
merged_filename: merged_UKR.txt
numeric_prefix_regex: ^\d+
on_bad_response: mark_for_manual
on_missing_copy_button: retry
output_folder: output
page_load_timeout: 10
response_timeout: 120
use_dom_method:
- copy_button
- js_full
- clipboard_via_js
- keyboard_copy
use_numeric_prefix: true

#template_message: # Один файл
#template_message: prompts/translate.txt  # відносний шлях (але не перевірено)
# Кілька файлів
template_message:
#  - d:\Python\TEXT\translation\KOD_pereclad\promt\translate1.txt              #початковий переклад
#  - d:\Python\TEXT\translation\KOD_pereclad\promt\translate2.txt              #редагування виправлення помилок
#  - d:\Python\TEXT\translation\KOD_pereclad\promt\translate3 Promt3.txt       #адаптація під пєсу/сценарій
#  - d:\Python\TEXT\translation\KOD_pereclad\promt\4_Adaptazija.txt            #Адаптація під теги уже переведений текст
  - d:\Python\TEXT\translation\KOD_pereclad\promt\nagolos+pausa.txt           #наголос і пауза
#  - d:\Python\TEXT\translation\KOD_pereclad\promt\promt.txt                   #індивідуальне завдання
#  - d:\Python\TEXT\translation\KOD_pereclad\promt\5.txt                       #індивідуальне завдання
#  - d:\Python\TEXT\translation\KOD_pereclad\promt\PROMPT_1_ПЕРЕКЛАД.txt
#  - d:\Python\TEXT\translation\KOD_pereclad\promt\PROMPT_2_ТЕГИ.txt
#  - d:\Python\TEXT\translation\KOD_pereclad\promt\PROMPT_3_АДАПТАЦІЯ.txt
  - d:\Python\TEXT\translation\KOD_pereclad\promt\teg.txt                     #Список тегів
#  - d:\Python\TEXT\translation\KOD_pereclad\promt\Golosary.txt                #Голосарій
  - d:\Python\TEXT\translation\KOD_pereclad\promt\--- ТЕКСТ ДЛЯ ВИПРАВЛЕННЯ ---.txt


# Старий текст прямо в YAML — теж продовжує працювати
#template_message: "Зробити переклад..."


